### ISSUE TITLE
aliases in the Parker et al 2020 GMM

### ISSUE THREAD

**Issue by ManuelaVillani** [gem/oq-engine#10133]
I have tried to use the Parker GMM with the alias for JP_PAC region and compare against the GMM where we explicitly set the region and saturation_region parameters. The ground motion estimates are different: 
![TrellisPlots](https://github.com/user-attachments/assets/378183fe-17c9-4df8-9123-086e5a6786a9)

**Comment by CB-quakemodel** [comment]
If these plots were generated in the comparison module, the issue is most likely that add_alias does not work when constructing GMMs from the toml (this is an odd bug I need to fix sometime). Therefore, the results from 'ParkerEtAl2020SInterJP_Pac' are being computed in effect from 'ParkerEtAl2020SInter' in reality here I think, explaining this disparity despite the fact the saturation region and attenuation region should in theory be the same. I will fix this soon, but the explanation of this add_alias bug in the SMT is explained in the docs here in case of interest: 

<img width="800" alt="image" src="https://github.com/user-attachments/assets/1ddd9f42-6b17-456d-b254-2b09bc35ef38">

**Comment by micheles** [comment]
This can be harder to fix than you think, @CB-quakemodel. Perhaps we should just raise an error when the user tries to use an alias. I need to see what is happening, @ManuelaVillani, please post here siome code.

**Comment by CB-quakemodel** [comment]
Yes I think raising an error (in the SMT - assuming this is how the attenuation curves were generated) when specifying an alias of a GMM could be a good idea. I've done some digging and as you say @micheles instantiating an alias from the toml is trickier than I initially thought it would be (the alias is created as a valid gsim object, but none of the expected arguments are attached as attributed - e.g. if specifiying AbrahamsonEtAl2014RegCHN, `self.region` is `None,` rather than `'CHN'`

**Comment by micheles** [comment]
You are probably instantiating the aliases incorrectly:
```python
In [1]: from openquake.hazardlib import valid
In [2]: valid.gsim('AbrahamsonEtAl2014RegCHN').region
Out[2]: 'CHN'
```
You *must* `valid.gsim(toml)` which is the only right way to instantiate a GSIM from its toml representation.
