### ISSUE TITLE
Remove the self-termination feature `terminate_job_when_celery_is_down`

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#1859]
This feature is more dangerous than useful, since if celery is slow to respond the job is automatically killed. It is best to leave time to the system instead. If the system hangs, let the system administrator to manage the situation. If you are on a single machine situation (no system administrator knowing what it is doing) you should use oq-lite instead, without celery.

**Comment by daniviga** [comment]
BTW this is a useful tool on a cluster, even with a sysadmin, because otherwise it's hard for a user to understand if a calculation is stuck because celery has failed or just because it's crunching data. We added it after a user reported a situation when he thought a computation was running instead celery failed silently and the (long) computation was stuck at some percentage.

**Comment by micheles** [comment]
The solution is to log better, not to automatically kill a job that does not respond fast enough.

**Comment by daniviga** [comment]
If we find a (better) way to identify if the workers are stuck or failed and then send (print) the error to the users, then lgtm

**Comment by daniviga** [comment]
We should also test more the behavior of `iter_native` in Celery 3.1. Maybe now it's already checking the workers availability (on Celery 2.5 it does not)
