### ISSUE TITLE
Ask for confirmation when deleting calc in webui

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2518]
See #2514 

In the modal we should ask for confirmation

**Comment by micheles** [comment]
Thinking a bit more about this issue, I realized that we do not need a confirmation dialog. When the user wants to delete a calculation? When it failed, otherwise she has little motive to remove it. So here is my proposal:

1. if the calculation failed, there is a "remove" button and it works without confimation
2. if the calculation did not fail, there is no "remove" button: the only way to remove the calculation is from the command-line.

This should be easy to implement, since the Javascript knows if a calculation failed or not (this info is used in the colors, red for failure, green for success).

**Comment by daniviga** [comment]
mmm I've seen the delete button used quite often during workshops to clean up successful calculations too, and during wss scientists tends to don't use the command line (and event to not explain in at all) so probably we have to keep it.
