### ISSUE TITLE
Add a job queue

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2575]
Now that Celery isn't used by most servers (they use multiprocess) we do not have any queue. This is increasing issue with computational resources. We should start thinking about a 'smart' job queue:

- We have e huge server booked and reserved for just exporting data (which is using 1 core and few MB of RAM)
- We have more than one user on a single machine: with celery the task are in a queue (which may be sub-optimal), with multiprocess everything tries to run with JOBS*CPU processes (2 jobs on a 32 cores machine are generating 64 processing trying to use 100% of CPU) causing a general slowdown ad high load average
- It's not easy to create an external queue right now, because external queue manager is not aware of in which phase the calculation is and then which resources is using/going to use.

**Comment by micheles** [comment]
The short term solution is to force the users to run the jobs via the webui, configurated so that the jobs are serialized (use python manage.py or nginx with a single worker). This requires zero effort but it is far from ideal. In the long term, we may switch to a professional queueing system such as the Grid Engine.

**Comment by daniviga** [comment]
This will be part of the discussion about SGE, for now our queue is the WebUI
