### ISSUE TITLE
Run a calculation on top of any kind of existing calculation

### ISSUE THREAD

**Issue by ptormene** [gem/oq-engine#2680]
As in https://github.com/gem/oq-irmt-qgis/pull/211, also using the Web UI it should be possible to run a calculation (e.g. a postprocessing) on top of either a hazard or a risk calculation (the name of the parameter `hazard_calc_id` is misleading).
We should also unify all the job.ini files in the demos, to have a single configuration file instead of two (`job_hazard.ini` and a `job_risk.ini`).

**Comment by daniviga** [comment]
It seems that the feature of passing an existing `calc_id` is actually broken: see #2682

**Comment by daniviga** [comment]
This feature is also untested, so we need to add a test.

**Comment by micheles** [comment]
Having separated `.ini` files has still its relevance, since I am thinking of implementing more post-processing calculators. It would still be convenient to unify the .ini files in the demos but it is so low priority that it won't be done any time soon.

Instead we should rename `--hazard-calculation-id` to `--parent-calculation-id` in the command-line interface. I would keep `--hc` as it is, without renaming it to `--pc`, to minimize changes.

**Comment by micheles** [comment]
Let's do nothing for the moment.
