### ISSUE TITLE
Should we change the csv export format for the scenario GMFs?

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2705]
Currently there is a number of columns equal to the number of ground motion fields, so if there a lot of samples, it is impossible to open the CSV in Excel and similar tools (the limit is around 1024). It would be more efficient to use the new CSV format that has been introduced for the event based, but it is a lot more cryptic.

**Comment by CatalinaYepes** [comment]
I don't think we should change the format, since it is not user friendly.
The new CSV format for EB is very complex to plot, since it does not include the coordinates of the points. The current format is easy to understand and it works well in QGIS.
Considering that in Excel 2010 there is a limit of 16,384 columns (LibreOffice or OpenOffice only support 1024 columns), it won't be a big problem to keep the format.
