### ISSUE TITLE
export event loss table for each asset

### ISSUE THREAD

**Issue by lmcsousa** [gem/oq-engine#2720]
I need to have access to the event loss table per asset. I understand that this feature was available in previous versions. Would it be possible to make it available again in the next issue?

Thanks
Luis Sousa

**Comment by micheles** [comment]
To see the asset loss table:

1. set `asset_loss_table= true` in the job.ini
2. run the computation and then use the command `oq export asset_loss_table`. An .hdf5 file will be generated containing the asset loss table.

The `asset_loss_table` will not appear within the regular outputs of the engine: this is on purpose, since it regular users should never need it. For power users, it is best not to use the exporter but to build your own post-processing script, using the code of the exporter as guidance.
