### ISSUE TITLE
Make it possible to specify the rupture distance

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#3403]
We should add a `filter_distance` variable in the job.ini, with default `rjb` and another possible value `rrup` (Marco says these are the only two choices).

**Comment by g-weatherill** [comment]
+1 to this change. We had to hack this to switch it to `rrup` for the PEER tests anyway. Unless there is a strong reason to keep the default as `rjb`, I would `rrup` the default instead.

**Comment by mmpagani** [comment]
I would suggest avoiding a default. This way the users will always decide exactly what they are doing. Your opinion?

**Comment by micheles** [comment]
No, we would break all existing calculations and everybody would be forced to change their job.ini files.
We MUST have a default. The most conservative is to keep the old one, i.e. rjb, but I am open to change it if you  two can agree ;-)

**Comment by g-weatherill** [comment]
Yes, that is another option. As long as it's clear in the manual I don't see a problem with it.

Incidentally, why only `rjb` and `rrup` as the choices? We still have some current GMPEs (mostly subduction in-slab) that use `rhypo` only.

**Comment by g-weatherill** [comment]
Fair point @micheles. For me, the preferred default distance would be `rrup`. This is because it is meaningful in all tectonic settings (shallow and deep), whereas`rjb` would not be an adequate reflection of the contribution of the source-site distance bin in cases where deeper events might dominate.

Admittedly, however, making this switch silently would create a potential inconsistency with previous results. So I defer to your's and @mmpagani 's final judgement on the matter.

**Comment by micheles** [comment]
Now that it is possible to specify the `filter_distance` in the job.ini I could run some tests. Thanks to the recent optimizations on the calculation of the `rrup` distance using scipy.spatial.distance I was expecting it to be faster than the `rjb` distance. This is indeed the case. For instance for SHARE:

using rjb, make_contexts: 159,226 seconds, called 332,812 times
using rrup, make_contexts:  80,615 seconds, called 332,812 times

The speedup is of a factor of two. In view of this fact, I am inclined to change the default `filter_distance` to `rrup`, as @g-weatherill wants.
