### ISSUE TITLE
rtree dependency problem

### ISSUE THREAD

**Issue by rizac** [gem/oq-engine#4341]
Hi all, I am using oq-engine and gmpe-smtk as backend library for a web service. Both are installed as editable (`pip install -e`) so that I can pull the latest versions/ edit files / issue PRs easily.
 
After updating the oq-engine library (pulling the last commit), this line of code

`from openquake.hazardlib import imt`

raised import error (`module rtree not found`). 

The problem was not solved after issuing

`pip install rtree==0.8.3`

Because I got:

`OSError: Could not find libspatialindex_c library file`

Finally, googling a bit, I needed (on MacOS):

`brew install spatialindex`

This now seem to work, but still I have two questions: 

- installing oq-engine as `pip install -e .`, `rtree` is not installed. This was ok until now, and in principle it's still ok, as in `setup.py` it is listed under 'extras_require', i.e. under optional features of the project. However, from the example posted above, `rtree` seems to be mandatory.
 - spatialindex seems to be also required. If yes, I did not find any mention about that. In case, it would be nice to add it to the documentation. If  it's already the case, please provide me the right link where I can check these kind of issues also in the future

Thank you very much

**Comment by daniviga** [comment]
> - installing oq-engine as pip install -e ., rtree is not installed. This was ok until now, and in principle it's still ok, as in setup.py it is listed under 'extras_require', i.e. under optional features of the project. However, from the example posted above, rtree seems to be mandatory.

Thanks for spotting this, we have updated the `setup.py` and moved `rtree` to the main requirements.

> - spatialindex seems to be also required. If yes, I did not find any mention about that. In case, it would be nice to add it to the documentation. If it's already the case, please provide me the right link where I can check these kind of issues also in the future

`libspatialindex` is not a direct requirement of the Engine and it is not either a Python library (that's why it cannot be declared in the `setup.py`). So you need to follow the upstream documentation for `rtree` (http://toblerity.org/rtree/install.html#nix) if you want to install it from sources. Otherwise we are providing binary wheels (python libraries that include also external dependencies) for the official Python installation (i.e. no Conda); it is documented here: https://github.com/gem/oq-engine/blob/master/doc/installing/development.md#install-openquake 

Unfortunately an `rtree` wheel is not provided by upstream on PyPi (like instead `numpy`, `scipy`, `shapely` ... do), so you have to manually use our requirements file.
