### ISSUE TITLE
Please implement oq celery start / stop commands

### ISSUE THREAD

**Issue by pini-gh** [gem/oq-engine#4344]
Hi,
It would be convenient to have 'oq celery start / stop' commands, working the same way as 'oq dbserver start / stop'.
Thanks in advance.

**Comment by micheles** [comment]
Uhm...
`oq` is a Python command, so internally it should do something like `subprocess.run(['ssh', ...])` to start/stop celery on the remote machines, so we should pass to it the IP addresses of the workers machines, set the SSH key correctly, managing the errors, consider all kind of custom situations (clusters, clouds, etc). I do not want to steal the job from sysadmins. Currently @daniviga has a script to start and stop the workers in our configuration and other sysadmins may have their own scripts depending on the settings on their own clusters. I do not think we can offer a general solution without forcing all people to use very specific settings.

**Comment by daniviga** [comment]
@pini-gh if you can be more specific about your use case we can work on an adequate solution.

Would you like to have an `oq celery start` that starts celery on remote workers? (as @micheles says)
or would you like to have just a wrapper for the celery starting command? (like https://github.com/gem/oq-engine/blob/master/debian/systemd/openquake-celery.service#L11).

The currently supported approach is to use systemd service unit installed on workers, which can then controlled via ssh or whatever.

**Comment by pini-gh** [comment]
I'm asked to install oq-engine on our cluster at $work, but I'm not allowed to setup such services as root and I have to manage everything in userspace. That's why such 'oq celery start / stop' commands would be convenient. A wrapper to start / stop the userspace service locally would suffice (the ssh part is easy). A command to start / stop the service on all remote workers would be great though.

**Comment by micheles** [comment]
I see, you are not the only one with this issue. What kind of cluster are you using? A better solution would be to use the cluster scheduler instead of celery. A substantial amount of work was done in the past to make it easy to integrate engine with any kind of schedulers, so I am convinced it can be done.

**Comment by pini-gh** [comment]
Thanks for considering :)
Our cluster runs a custom Debian 8 derivative and uses the SLURM scheduler.

**Comment by micheles** [comment]
That's interesting to know. The issue is that we do not have a cluster that we can use for development, so we could not work on this kind of projects much. If you want this to be done is to donate us access to a SLURM cluster ;-)

**Comment by pini-gh** [comment]
Can't do that :)
But with some inputs from your side I could fix / improve what has been done to support schedulers and contribute it back. I'd just need to know where to start.

**Comment by micheles** [comment]
Until engine-2.9 we had experimental support for the grid engine, see for instance
https://github.com/gem/oq-engine/blob/engine-2.9/openquake/baselib/parallel.py (search for "qsub").
We tried it on a workstation and it was working but it was slow. Then we removed the support because without having a cluster and without automatic tests for the feature it was impossible to maintain it.
It was just a proof of concept from the beginning. But you can get some idea.

**Comment by micheles** [comment]
Closing because we are not going to implement oq celery start/stop for the moment.
