### ISSUE TITLE
Unify scenario_damage and scenario_risk into a single scenario_risk calculator

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#4575]
It will compute damages or losses or both depending on the risk functions passed to it.
This was requested by @CatalinaYepes 

The keep compatibility with the past, `calculation_mode=scenario_damage` will keep working, but it will be an alias for `scenario_risk`.

The manual will need to be updated.

**Comment by CatalinaYepes** [comment]
the idea behind is to simplify the number of calculators in the engine, since a single `scenario_risk` calculator could provide all the options:

- If the user assigns only fragility, then only damage is computed
- If the user provides fragility and consequence, then damage and losses are computed
- If the user provides fragility and vulnerability, then damage and losses are computed
- If the user provides only vulnerability, then only losses are computed


NOTE: We have to be careful with occupants, since currently is only supported in scenario_risk calculations. However, I think the idea in the future will be also to improve and extend the way human losses are estimated in the engine @raoanirudh

**Comment by micheles** [comment]
I have already merged 11 (eleven!) pull request towards this goal and we are still far from reaching it. Plus there will be changes required to the manual and most importantly to IPT. Changing IPT is a **huge** thing, so for the moment I am closing this ticket. Let's keep the status quo.
