### ISSUE TITLE
Docker Port Requirements for Kubernetes 

### ISSUE THREAD

**Issue by wshelley** [gem/oq-engine#4622]
Would it be possible to list which ports need to be opened on the master, worker and queue?

These are specifically needed for kubernetes configuration. I think I’ve managed to get most of them using netstat, but want to double check.

Happy to share the working kubernetes config via a PR if it is useful, as you don’t seem to have one in your repo at the moment.

**Comment by daniviga** [comment]
Hi @wshelley, thanks for your contribution.

No, we do not have currently a configuration for k8s: we are not aware of any user deploying the Engine on Kubernetes (most container users are running multiple ephemeral instance of a single Docker). I would indeed be very happy to publish it in our official repo.

You can find the list of ports here: https://github.com/gem/oq-engine/blob/master/doc/installing/cluster.md#network-and-security-considerations

## Broker (RabbiMQ)

Needs at least port `5672/tcp`. `15672/tcp` should be also exposed if you want to monitor it via the [management plugin](https://www.rabbitmq.com/management.html)

## Master

Needs:
- `1908/tcp` for the DbServer (in the page `1907` is stated because when using deb and rpm packages we set a different port)
- `1912-1920/tcp` for the ZeroMQ receivers (where tasks results are sent back)
- `8800/tcp` for the API/WebUI server

## Workers
No listening ports, but they need indeed to be able to communicate with master on `1912-1920/tcp` and broker `5672/tcp`

Please also note that workers must be able to read the `oqdata` folders from master when running on multiple nodes: see https://github.com/gem/oq-engine/blob/master/doc/installing/cluster.md#shared-filesystem and https://github.com/gem/oq-engine/blob/master/docker/docker-compose.yml#L60 as references.

If anything is not clear enough let us know, will try to explain and document it better.

**Comment by daniviga** [comment]
@wshelley should I close this?

**Comment by wshelley** [comment]
Thank you for the port details, I can confirm these work. Hopefully I will have time to do some more testing then I can provide the working kubernetes manifest files for deploying the oq engine.
