### ISSUE TITLE
Add 'shape_descr' key to agg_curves-rlzs

### ISSUE THREAD

**Issue by ptormene** [gem/oq-engine#4982]
It was added to agg_curves-stats only

**Comment by micheles** [comment]
This is not a bug, the attribute was not added because I did not expect to plot the agg_curves-rlzs and I still think it is a bad idea. Reason: normally there are 100+ realizations, any plot of 100+ curves is ugly and unreadable. Anyway, I am adding it anyway for consistency and there could even be cases with few realizations well plots could actually make sense.
