### ISSUE TITLE
Reduce the event ID length from 64 bit to 32 bit

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5041]
To make Excel happy.

**Comment by micheles** [comment]
Here the complete list of changes:

1. the formula rup_id == event_id / 2^32 does not work anymore
2. in the events table there is a new field rup_id
3. in the events table the field rlz has been renamed to rlz_id

**Comment by raoanirudh** [comment]
For context: the event loss tables are commonly opened and viewed in MS Excel or other similar spreadsheet applications. 

Excel has a maximum precision of 15 significant digits, so for any number containing 16 or more digits like the current event_ids, all numbers past the 15th digit are rounded down to zero. Excel also automatically removes leading zeros from the event_ids, and converts them to scientific notation. The only way to avoid this mangling by Excel is to import the tables and force Excel to read the event_id column as text rather than as numbers, but this is a very tedious workaround.

**Comment by raoanirudh** [comment]
Another incentive for shorter event_ids is the potential reduction in file sizes. For an event set with one million events, just storing the column of 16-digit event_ids takes up 17MB.
