### ISSUE TITLE
Deprecate the rupture XML exporter

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5379]
It is the last one of the old XML exporters and as @CatalinaYepes pointed out it is hopelessly verbose for the calculations we run now and does not contain all the information we want. The best candidate to replace it is the TOML exporter, see https://github.com/gem/oq-engine/issues/5277, which generates a file that can also be imported. It has to be extended to manage more one rupture, though, and it must provide additional information like which was the source that generated the rupture.

**Comment by CatalinaYepes** [comment]
The discussion about the `ruptures.xml` is related to the inefficient way we are storing the information. Moreover, if the user wants to run a Scenario calculation using a generated rupture from an Event_Based calculation, the format is not compatible (#5277).

I think introducing an option for exporting a specific rupture can be useful, but why generating another type of `rupture input file`? Since the user will only export one rupture, why not to keep the xml format that the engine is currently using for input files?

We are introducing here three main changes:
1) Removing the ruptures.xml
2) Adding the option to extract a specific rupture
3) Changing format to TOML

Maybe the TOML format will make sense for the exporter of all ruptures. From the single rupture file, from the user perspective, it will be nicer to keep the xml input format.

**Comment by micheles** [comment]
The problem is that it is a lot of work to write an XML parser for reading a rupture working for all kinds of ruptures, while the TOML format is trivially convertible to rupture objects. BTW, I do not propose to remove the parser that we have to read ruptures in XML, so all the scenarios that we have will keep working unchanged.
