### ISSUE TITLE
Fix compatibility between gmfs.csv input and output format in event_based calculations

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5386]
If the user runs an `event_base` calculation and wants to use the gmfs.csv as input data in a risk calculation, the format is not compatible:

- Headers do not match (`event_id` vs `eid`, `site_id` vs `sid`)
- The `rlz_id` column is not included
- The engine only accepts gmfs.csv files that have a monotonically increasing `event_id` value starting from zero (i.e, from 0 up to the length of the events).

This can also be related with issue #5327

**Comment by micheles** [comment]
Remember that there are limitations so that if there is more than one realization this will never work. If the goal is to amplify the GMFs of an event based calculation just say so and there are much better ways of doing that, and I am going to implement that next year once Marco Pagani gives me the specs.
