### ISSUE TITLE
Say no to the proliferation of GSIM classes

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5408]
5 years ago it was impossible to pass parameters to a GSIM, so it was necessary to define a different GSIM class for each typology of GSIM. Now it is possible to pass parameters to a GSIM, but still people are writing down tons of different GSIM classes without a good reason. Take for instance the NBCC2015_AA13 classes:
 ```
NBCC2015_AA13_Base
NBCC2015_AA13_activecrustFRjb_low
NBCC2015_AA13_activecrustFRjb_central
NBCC2015_AA13_activecrustFRjb_high
NBCC2015_AA13_interface_low
NBCC2015_AA13_interface_central
NBCC2015_AA13_interface_high
NBCC2015_AA13_activecrust_low
NBCC2015_AA13_activecrust_central
NBCC2015_AA13_activecrust_high
NBCC2015_AA13_inslab30_low
NBCC2015_AA13_inslab30_central
NBCC2015_AA13_inslab30_high
NBCC2015_AA13_inslab50_low
NBCC2015_AA13_inslab50_central
NBCC2015_AA13_inslab50_high
NBCC2015_AA13_offshore_low
NBCC2015_AA13_offshore_central
NBCC2015_AA13_offshore_high
NBCC2015_AA13_stablecrust_low
NBCC2015_AA13_stablecrust_central
NBCC2015_AA13_stablecrust_high
```
There are 22 classes while there should be only one accepting three parameters REQUIRES_DISTANCES, DEFINED_FOR_TECTONIC_REGION_TYPE, gmpe_table.
The situation for the recent PR https://github.com/gem/oq-engine/pull/5406 is even worse. Fortunately, I figured out a way to reduce the number of classes while at the same time keeping backward compatibility and I applying it first to the NBCC2015_AA13 classes. Next, it can be applied to the NGAEast classes, but probably https://github.com/gem/oq-engine/pull/5406 should be merged first. Another candidate for reduction are the 15 NSHMP classes which can be become 1.

**Comment by g-weatherill** [comment]
I completely support this; hence me implementing the next generation European GMPEs along these lines rather than many subclasses. Would you like me to refactor the CEUS GMPEs in https://github.com/gem/oq-engine/pull/5406 in this manner? I had retained the full set of subclasses mostly for clarity and consistency with the US NSHMP software. 

I would make one minor comment, however, which is that that the passing of parameters to GMPEs is not well-documented in the manual, so most users are unaware of this or would know how to build the logic tree files accordingly. Furthermore, as different GMPEs take different arguments could there be a better way to document which arguments can be passed to which GMPEs (and what the arguments actually control in the respective GMPE) without having to refer the user to the API docs?

**Comment by micheles** [comment]
I would not change  #5406; the tests are green, let's merge (if @mmpagani agrees). After the merge I want to refactor it to avoid the subclasses. I wanted to do so from a long time, but until today I did not have an elegant mechanism to keep backward compatibility. Now thanks to the `gsim_aliases` I can keep the gsim logic tree files as before and instantiate the right gsims, without needing the subclasses.

About the docs, parametric GMPEs are documented in the manual for advanced users: https://github.com/gem/oq-engine/blob/master/doc/adv-manual/parametric-gmpes.rst
People implementing new GMPEs are advanced uses, so I feel it is the right place where to put the information.
