### ISSUE TITLE
Decide what to do if the exposure CSV has a field named "id"

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5457]
It will conflict with the engine "id", i.e. the asset_ref.

**Comment by raoanirudh** [comment]
The exposure files will _always_ have an 'id' field ([example](https://github.com/gem/oq-engine/blob/engine-3.8/demos/risk/ScenarioRisk/exposure_model.csv)). This is a mandatory field. Do you mean an additional tag which is also called 'id'?

**Comment by micheles** [comment]
I need exactly that @raoanirudh

**Comment by raoanirudh** [comment]
The user-specified field names must be case-sensitive, since the field names in the exported files need to be identical to those defined in the exposure metadata xml, mainly to facilitate vlookups or joins in post-process. There is more flexibility on the mandatory fields since these are always treated as lowercase in the engine and in the outputs; so these could be made case-insensitive for the input exposure csvs.

**Comment by micheles** [comment]
Currently having a tag called "ID" because it would not conflict with the "id". However, users may get confused, so it is probably better to forbid to have name which are equal apart from the case. But would we break something? I don't think so but I would hear your position on that,

**Comment by pslh** [comment]
I think permitting tags which differ only by case is more likely to be an error than not.  I agree that we should preserve case when we output but perhaps we should be checking for case-independent uniqueness before we start calculations
