### ISSUE TITLE
Disaggregation Matrix is too Large

### ISSUE THREAD

**Issue by volkanozsarac** [gem/oq-engine#5784]
Dear Developers,

I am performing PSHA for a single site using SHARE model for seismic sources. As an output I am trying to obtain hazard curves and disaggregation information. I am able to obtain hazard curves, yet the engine gives the following error and stops working while performing disaggregation.
"The disaggregation matrix for site #0 is too large (1769040 elements): fix the binning."
I am using openquake v3.9.0. I wonder if the issue is related to capacity of PC I am using or input that I am providing. Following input is provided for [disaggregation].

[disaggregation]
poes_disagg = 0.9, 0.7, 0.5, 0.3, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.0025, 0.001
mag_bin_width=0.5
distance_bin_width=10.0
coordinate_bin_width=0.2
num_epsilon_bins=3
disagg_outputs = Mag_Dist, Mag_Dist_Eps

My best regards,

![image](https://user-images.githubusercontent.com/46993652/80501895-a7a65c80-8978-11ea-9f18-332f34e07836.png)

**Comment by micheles** [comment]
On Tue, Apr 28, 2020 at 4:52 PM Volkan Ozsarac <notifications@github.com>
wrote:

> Dear Developers,
>
> I am performing PSHA for a single site using SHARE model for seismic
> sources. As an output I am trying to obtain hazard curves and
> disaggregation information. I am able to obtain hazard curves, yet the
> engine gives the following error and stops working while performing
> disaggregation.
> "The disaggregation matrix for site #0 is too large (1769040 elements):
> fix the binning."
> I am using openquake v3.9.0. I wonder if the issue is related to capacity
> of PC I am using or input that I am providing. Following input is provided
> for [disaggregation].
>
> [disaggregation]
> poes_disagg = 0.9, 0.7, 0.5, 0.3, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005,
> 0.0025, 0.001
> mag_bin_width=0.5
> distance_bin_width=10.0
> coordinate_bin_width=0.2
> num_epsilon_bins=3
> disagg_outputs = Mag_Dist, Mag_Dist_Eps
>
> My best regards,
>
> [image: image]
> <https://user-images.githubusercontent.com/46993652/80501895-a7a65c80-8978-11ea-9f18-332f34e07836.png>
>


The relevant line in your log is the one that says

nbins = {'mag': 9, 'dist': 20, 'lon': 26, 'lat': 18, 'eps': 3, 'trt': 7}

Now 9*20*26*18*3*7 = 1,769,040, which is the size of your disaggregation
matrix, way too much. You must reduce the number of bins, as the error
message says.
I would reduce the number of lon, lat bins. For that, just change from
coordinate_bin_width=0.2 to  coordinate_bin_width=1 and you will reduce
your disaggregation
matrix by a factor of 25, that should be enough. Otherwise, reduce even
more. There is also an FAQ:

https://github.com/gem/oq-engine/blob/master/doc/faq-hazard.md#i-am-getting-an-error-disaggregation-matrix-is-too-large

HTH,

              Michele

**Comment by micheles** [comment]
NB: the mailing list is the right place for questions, not GitHub!

**Comment by volkanozsarac** [comment]
Thanks a lot for the information, sorry for posting this question on GitHub.
