### ISSUE TITLE
Add an exporter for src_loss_table

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#5788]
It should export a column for each loss type, ordered by the first loss type.

**Comment by CatalinaYepes** [comment]
The goal of this output is to provide a better understanding of the contribution of sources and TRTs to losses.

This output will derive from the from the `extract_src_loss_table(dstore, loss_type)`. Currently the `src_loss_table` is an hdf5 with the following information:

|source_id  | grp_id |  loss_type |
| --------- | ------ | ---------- |
|source_01 | 0 | 50,000 |
|source_02 | 0 | 1,000 |
|source_03 | 1 | 2,500 |
|source_04 | 1 | 17,000 |


The idea will be to generate the output `losses_per_trt_src.csv`.
It will be required:
- Change format to .csv
- All possible loss_types should be appended to the columns. The values will be ordered by the first loss_type.
- Instead of including the `grp_id` field, include the `trt`
- Reorder columns

|trt | source_id | loss_type |
|------------ | ------------ | ------------|
Active Shallow Crust | sourcce_01 | 50,000 |
Active Shallow Crust | sourcce_02 | 1,000 |
Subduction Interface | sourcce_03 | 2,500 |
Subduction Interface | sourcce_04 | 17,000 |

**Comment by CatalinaYepes** [comment]
To be consistent with other outputs, the csv output should not append the columns for each loss_type, but instead have a column for the `loss type`

|trt | source_id | loss_type | loss_value |
|------------ | ------------ | ------------| ---------|
Active Shallow Crust | source_01 | structural | 50,000 |
Active Shallow Crust | source_02 | structural | 17,000 |
Subduction Interface | source_03 | structural | 2,500 |
Subduction Interface | source_04 | structural | 1,000 |
Active Shallow Crust | source_01 | nonstructural | 10,000 |
Active Shallow Crust | source_02 | nonstructural | 8,250 |
Subduction Interface | source_03 | nonstructural | 740 |
Subduction Interface | source_04 | nonstructural | 600 |

**Comment by CatalinaYepes** [comment]
The current exporter is summing up all losses for a given source, but the results should be disaggregated per rlz or per stats.

For example, for `case_master` the difference is shown here:

Current `src_loss_table-structural.csv` :
|source_id  | grp_id |  structural |
| --------- | ------ | ---------- |
| 2	|	2	|	17498.152	|
| 1	|	1	|	2689.2231	|


Output for `stats` should be:
| trt | source_id |  loss_type |	stats |	loss_value	|
| --------- | ------ | ---------- |	--------- |	--------- |
| Stable Shallow Crust	|	2	|	structural |	mean	|	2231.82	|
| Active Shallow Crust	|	1	|	structural |	mean	|	4555.15	|
| ...	|	...	|	nonstructural |	...	|	...	|

Output for `rlz` should be:
trt	|	source_id	|	rlz_id	|	loss_type	| loss_value	|
-----------	|	-----------	|	-----------	|	-----------	|	-----------	|
Stable Shallow Crust	|	2	|	0	|	structural	|	2131.984	|
Stable Shallow Crust	|	2	|	1	|	structural	|	4992.33	|
Stable Shallow Crust	|	2	|	2	|	structural	|	2992.973	|
Stable Shallow Crust	|	2	|	3	|	structural	|	7380.86	|
Active Shallow Crust	|	1	|	4	|	structural	|	489.828	|
Active Shallow Crust	|	1	|	5	|	structural	|	657.809	|
Active Shallow Crust	|	1	|	6	|	structural	|	464.537	|
Active Shallow Crust	|	1	|	7	|	structural	|	1077.05	|
…	|	…	|	…	|	nonstructural	|	…	|

**Comment by micheles** [comment]
I am model like Australia there 1M sources, 100 realizations and 2 loss types, so the matrix becomes difficult to manage. I would just generate the src_loss_table for the mean: that would also make it possible some optimizations.
