### ISSUE TITLE
Extend ignore_covs to Beta vulnerability functions

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#6105]
Currently the `ignore_covs` parameter works only with lognormal vulnerability functions. The user expectation would be that the same behavior should also apply for Beta vulnerability functions.

**Comment by micheles** [comment]
For the lognormal distribution ignore_covs=true is the same as assuming that the all the covs are zero. However for the beta distribution covs == 0 is an error (see https://github.com/gem/oq-engine/pull/6259). Should we make setting ignore_covs=true
an early error in that case?

**Comment by raoanirudh** [comment]
For the lognormal distribution, we handle the ignore_covs case by switching the distribution: https://github.com/gem/oq-engine/blob/master/openquake/risklib/scientific.py#L161-L162. Can we do the same for the beta distribution?

**Comment by micheles** [comment]
I forgot about that. Let me check.

**Comment by micheles** [comment]
The situation is trickier than expected. I though ignore_covs=true was setting covs=0 and the setting the DegenerateDistribution. Instead for lognormal if the original covs are nonzero, even if ignore_covs is true they are kept nonzero and therefore the DegenerateDistribution is not used. We could treat that as a bug and change the behavior. What do you think?
For the global mosaic nothing would change since when we ran it two years ago we used covs=0 inside the vulnerability functions so the DegenerateDistribution was really used.

**Comment by raoanirudh** [comment]
Setting `ignore_covs = 0` should result in the same behavior as having all covs = 0 inside the vulnerability model file, so I think ideally we should be using the same logic within the engine to handle both of these cases.
