### ISSUE TITLE
ID for sites

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#6497]
Check if sites can have an ID parameter (say in a .csv site model file). If not, add it and make sure that it's also added to the outputs (e.g. UHS, HCs).

**Comment by micheles** [comment]
The site_model.csv can contain a field called `custom_site_id` which the only requirement of being an unique number (the risk use it to store zip codes). So if the `custom_site_id` is there you want to export it, otherwise you want to export the incremental `site_id` that the engine uses internally, right?

**Comment by mmpagani** [comment]
I think it would be quite useful having something like this:
```
siteID,lon,lat,vs30,z1pt0,z2pt5,vs30measured
PIPPO,-1.00,1.00,800.0,31.07,0.57,1
```
where 'PIPPO' is added to the UHS and HC output. In this way it's easy to map init Vs output. Otherwise, I can continue using the coordinates although it's less efficient IMO.

**Comment by g-weatherill** [comment]
+1 To Marco's suggestion. Having a more general site ID like the one he describes would make sense for users who perhaps want to run calculations for a larger set of towns/cities in the country. It helps make the results clearer.
