### ISSUE TITLE
Universal install script: modifications needed for Windows

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#6695]
1. Python on Windows does not have the module `pwd`, so the import may need to be skipped on Windows
2. The _venv_/bin/ directory on Linux/Mac is called _venv_/Scripts/ on Windows, so the script is unable to find `pip`
3. In the printed messages, forward slashes should be printed as backslashes instead on Windows

Other potential issues: 
- `getpass.getuser()` can fail on Python 3.6 on Windows, and the error message is related to the failure to `import pwd`

Thanks to @jamaldabbeek for testing the script on Windows

**Comment by micheles** [comment]
About getpass.getuser there is nothing better to my knowledge. It fails on Windows if no environment variables are set (one of LOGNAME, USER, LNAME, USERNAME at least according to the documentation
https://docs.python.org/3/library/getpass.html#getpass.getuser). Since the WebUI works on Windows and has been working for nearly 10 years I assume that normally the environment variables are set.

**Comment by raoanirudh** [comment]
@micheles, @vot4anto, please check the doc page for the universal installer too – the instructions for Windows may need to be separated from Unix/macOS, since the paths are slightly different.
