### ISSUE TITLE
Refactoring of hazardlib: phase 3 (recarray)

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#6973]
The third phase of the plan described in https://github.com/gem/oq-engine/blob/master/doc/breaking-hazardlib.md is to vectorize by  rupture which in practice means: instead of many contexts with small arrays, pass to the GMPEs a single context with large arrays. Here is where the speedup arises. In the case of the `test_single_site` the measure speedup in `get_mean_stds` is 200x.
We need to convert the contexts into a single `numpy.recarray` object and then to change all GMPEs to make them accept the recarray. GMPEs that have been converted can be recognized by the type annotation `ctx: np.recarray` in the signature of the `.compute` method.

**Comment by cbworden** [comment]
I get that you are doing a major refactor of hazardlib, and whether I agree with the way you are doing it or not, what I don't understand is why you are merging it into the master repo in this piecemeal fashion. Why did you not create a new branch (called something like "new-hazardlib") and do all of your refactoring there? Then, when you were done, you could have made an announcement and pushed the new branch to master. As it is, we users of hazardlib are forced to constantly keep up with any changes you make that affect us, rather than doing them all at once and being done with them.

**Comment by micheles** [comment]
I cannot keep something of this magnitude in a separate branch. Merging a piece at the time allows me to find errors soon (the issues are always with interacting with code *external* to the engine) and to fix them as soon a possible. If I kept a huge branch for 3 months outside of master then at the single big merge dozens of issues would come up at the same moment making it impossible (or extremely difficult) to sort them out. I believe the end result would be worse even for the final users. You can just avoid upgrading the master all the time. Keep a version that works for you and wait for the end of the refactoring.
I am making a huge effort to keep the breakage for the final user to a minimum and we are very responsive towards any reported bug due to the refactoring.
