### ISSUE TITLE
To fix in eb-damage calcualtor

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#7130]
# TO IMPROVE IN EB-DAMAGE

## Outputs content

- [x] agg_curves
   - aggcurves are missing columns for `loss_ratio` and `annual_frequency_of_exceedence`
   - When adding the loss_ratio column, then it will be needed to modify the output to list consequence_type in a column.
   We can think of calling it also `loss_type` to match the eb-risk output (and drop the current loss_type columns)

- [ ] suggestion:
   We could consider adjusting the `risk_by_event` output of the eb-risk to report the loss_type value per column.
   It will significantly reduce the length and size of the file (plus it will look similar to the eb-damage)

## Names displayed in terminal
- [x] eb-damage is missing the following outputs, compared with eb-risk
```
   Aggregate Losses Statistics --> Aggregate Risk "Statistics"
   Source Loss Table           --> Source Loss Table 
```

- [x] The eb-risk outputs have all the “Statistics at the end, while eb-damage don't have it. 
       Adjust names displayed in terminal to match eb-risk
```
   Asset Risk Distributions  --> "Average" Asset Risk "Statistics"
   Aggregate Risk Curves  --> Aggregate Risk Curves "Statistics"
```
| eb-rik | eb-damage |
| ------ |---------- |
| Aggregate Loss Curves Statistics | Aggregate Risk Curves |
| Aggregate Losses Statistics  | ? |
| Aggregated Risk By Event  | Aggregated Risk By Event |
| Average Asset Losses Statistics | Asset Risk Distributions |
| Earthquake Ruptures   | Earthquake Ruptures |
| Events     | Events |
| Full Report |  Full Report |
| Ground Motion Fields  | Ground Motion Fields |
| Input Files |  Input Files |
| Realizations    | Realizations |
| Source Loss Table           | ? |

## Output file names

- [ ] Adjust eb-damge output `aggcurves_CalcID.csv` --> `agg_curves-rlz-000_CalcID.csv`

- [ ] The output `agg_losses-mean` is missing compared to eb-risk: 

| eb-rik | eb-damage |
| ------ |---------- |
| agg_curves-rlz-000.csv | aggcurves.csv |
| agg_losses-rlz-000.csv | ? |
| avg_losses-mean.csv    | ? (we should diplay the mean) |
| avg_losses-rlz-000.csv | avg_risk-rlz-000.csv |
| risk_by_event.csv      | risk_by_event.csv |

**Comment by micheles** [comment]
@CatalinaYepes , the event_based_damage calculator is DIFFERENT from the event_based_risk calculator and CANNOT produce the same outputs. For instance,  what would be the equivalents of loss_ratio and annual_frequency_of_exceedence if used to compute the "homeless" consequence? A "homeless_ratio" and "annual_frequency_of_exceedence"? Would that be clear to the final user? In doubt I preferred not to add columns that anyway can be computed with a postprocessing script.
This is also the reason why the output Source Loss Table is missing, it would be replaced by a very unclear "Source Homeless Table" (?)
Statistical outputs are missing because the Event Based Damage calculator works effectively with a single realization.
