### ISSUE TITLE
Can't import AbrahamsonEtAl2014RegCHN

### ISSUE THREAD

**Issue by cbworden** [gem/oq-engine#7219]
I'm unable to import AbrahamsonEtAl2014RegCHN, AbrahamsonEtAl2014RegJPN, or AbrahamsonEtAl2014RegTWN, but I can import AbrahamsonEtAl2014:
```
In [1]: from openquake.hazardlib.gsim.abrahamson_2014 import AbrahamsonEtAl2014RegCHN
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-9c26395c3f26> in <module>
----> 1 from openquake.hazardlib.gsim.abrahamson_2014 import AbrahamsonEtAl2014RegCHN

ImportError: cannot import name 'AbrahamsonEtAl2014RegCHN' from 'openquake.hazardlib.gsim.abrahamson_2014' (/Users/cbworden/anaconda3/envs/shakemap/lib/python3.8/site-packages/openquake/hazardlib/gsim/abrahamson_2014.py)

In [2]: from openquake.hazardlib.gsim.abrahamson_2014 import AbrahamsonEtAl2014

In [3]: 
```

**Comment by micheles** [comment]
`AbrahamsonEtAl2014RegCHN` is an alias. This is a concept we introduced 1 or 2 years ago and we have been using more recently:
````python
>>> from openquake.hazardlib.gsim.base import gsim_aliases
>>> gsim_aliases['AbrahamsonEtAl2014RegCHN']
"[AbrahamsonEtAl2014]\nregion = 'CHN'"
```
AbrahamsonEtAl2014RegCHN is an instance of AbrahamsonEtAl2014 with parameter region="CHN". The idea is to use parametric GMPEs instead than subclasses. See https://docs.openquake.org/oq-engine/advanced/parametric-gmpes.html
and the last three lines of https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/abrahamson_2014.py.
In practice, just subclass from AbrahamsonEtAl2014 and not from AbrahamsonEtAl2014RegCHN.

**Comment by micheles** [comment]
You are making a mountain of a molehill. You want to know which are the aliases? `print(gsim_aliases)`, done. You want to produce a AbrahamsonEtAl2014RegCHN GSIM from the string? Call `openquake.hazardlib.valid.gsim("AbrahamsonEtAl2014RegCHN")`, done.

Having dozens of subclasses when a single class would have been enough was an embarassing design error that has been there for 10 years, and I took the occasion to fix it. Old users can fix their scripts with a small change in the imports, new users will thank me because now they will have to learn a single class instead of a hierarchy of 10+ subclasses. 

Having said that, it is in unlikely that new aliases will be added, since they are only a compatibility trick to keep the old names working, hopefully the next GMPEs will be implemented properly. The last change in the aliases has probably already been implemented, see https://github.com/gem/oq-engine/pull/7184/files.

**Comment by cbworden** [comment]
**_"You are making a mountain out of a molehill."_**

Thanks for trivializing the redesign we are going to have to do.

**_Having dozens of subclasses when a single class would have been enough was an embarassing design error that has been there for 10 years, and I took the occasion to fix it._**

So now because of your arbitrary and capricious design decisions, instead of a uniform set of classes that could be treated exactly the same everywhere and in every way, there are two different types of objects and the way to tell them apart is by **printing them out** and combing through the results, and then going through our code and creating `if` and `try` blocks everywhere we access any of these entities. Yeah. There's nothing embarrassing about that at all. 🙄
