### ISSUE TITLE
Question: Any plans for having interpolation for those models with limited periods? (SA intensity measure)

### ISSUE THREAD

**Issue by SnowNooDLe** [gem/oq-engine#7678]
Hey all,

There are a few models we are using and we noticed that `Zhao_2006` only supports periods between 0.05 ~ 5.0 for SA intensity measure when most other models we use, support the periods between 0.01 ~ 10.0. (For instance, Bradley_2013 and Kuehn_2020 support period between 0.01 ~ 10.0)

So we were wondering whether you guys have any interpolation that can solve models with limited periods
(As far as I am aware, even running contexts module's `ContextMaker.get_mean_stds()` still triggers an error saying no such period with this model, which is expected as we do not see that `ContextMaker.get_mean_stds()` does any magic on periods part yet.)
or plan to implement the interpolation to support more periods?

**Comment by micheles** [comment]
From what I understand, when the engine gives an error for a given period, it is because for that period the GMPE is invalid, so there is nothing to do except to use a different GMPE. Extending the validating range of GMPE requires extending the GMPE, you cannot just extrapolate the results outside the validity range.

**Comment by SnowNooDLe** [comment]
Sorry for the late response but I appreciate your response.

We will see what we can do.
