### ISSUE TITLE
V3.13 and 3.14 use h5py==3.1.0 which is not compatible with the requirements (>=2.10)

### ISSUE THREAD

**Issue by f-combes** [gem/oq-engine#7839]
Outputs from the docker image of the engine, for version 3.13 and 3.14 cannot be read when the installed version of h5py is 2.10. 

From setup.py, on tags v3.13.0 and v3.14.0:
```python
install_requires = [
    ...
    'h5py >=2.10',
    ...
]
```
From `pip freeze` in the docker images (3.13 and 3.14 tags)
> h5py @ https://wheelhouse.openquake.org/v3/linux/py38/h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl
While version 3.12 has
> h5py @ https://wheelhouse.openquake.org/v3/linux/py38/h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl

Proposed solution: bump required h5py version to 3.1.0

**Comment by micheles** [comment]
Unfortunately, looking at the setup.py is not enough. You should have looked at the files requirements.txt files, where h5py  3.1.0 is listed. The setup.py is correct since it is true that the engine works with h5py==2.10 and its outputs could be read by using the same version of h5py. But the docker version includes h5py==3.1 (because it is listed in the requirements.txt) and this is the version you must use to read the generated datastores.
