### ISSUE TITLE
Tie the advanced manual to the engine version

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#8119]
Currently it is generated only for master and it is impossible to go back to old versions (unless one looks at github). It should be put in standard places (latest, stable, X.Y.Z) as the regular manual.

**Comment by raoanirudh** [comment]
The template we're using also has an option to add a button that allows users to switch between versions of the documentation:
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html

**Comment by micheles** [comment]
@nastasi-oq, can we close this now?

**Comment by CatalinaYepes** [comment]
Here is a screenshot of the drop-down button taken from pandas documentation
@nastasi-oq 
<img width="1312" alt="Screenshot 2023-01-10 at 11 31 22" src="https://user-images.githubusercontent.com/6975363/211527688-2199b5db-30b0-4e15-9794-5c8dd19f3e1c.png">

**Comment by nastasi-oq** [comment]
I'm working on this new feature and I will extend it to the "user manual" too.
Take in account that after the next release the dropdown will be populated with just 2 items:
```
3.16 LTS
master (target 3.17)
```
and so on for the next not LTS releases
```
3.16 LTS
3.17
master (target 3.18)
```
...

The effort to produce previous advanced manual versions would not be negligible and if you need it it must be discussed because not already implemented for github actions.
