### ISSUE TITLE
Fix display name for reinsurance outputs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#8122]
Despite having indicated in `actions.py` the names to display for the reinsurance outputs, 
```
DISPLAY_NAME = {
        ...
        'reinsurance-aggrisk': 'Average Reinsurance By Policy',
        'reinsurance-avg_losses': 'Average Reinsurance',
        'reinsurance-risk_by_event': 'Reinsurance By Event',
        'reinsurance-aggcurves': 'Aggregated Reinsurance Curves',
        ...
        }
```
the engine currently shows after a calculation the following names:

```
  id | name
   ...  |  ...
 330 | Source Loss Table
 324 | reinsurance-aggcurves
 325 | reinsurance-aggrisk
 326 | reinsurance-avg_losses
 327 | reinsurance-risk_by_event
```

**Comment by micheles** [comment]
Did you try to do `oq dbserver stop` and then `oq dbserver start`? The new names appears only after a restart of the DbServer.

**Comment by CatalinaYepes** [comment]
Shall we also try to adjust the names of the outputs 

from:
```
'reinsurance-aggrisk': 'Average Reinsurance By Policy',
'reinsurance-avg_losses': 'Average Reinsurance',
```
to:
```
'reinsurance-aggrisk': 'Aggregated Reinsurance',
'reinsurance-avg_losses': 'Average Reinsurance By Policy',
```

**Comment by micheles** [comment]
The issue is that both 'reinsurance-aggrisk' and 'reinsurance-avg_losses' are DIFFERENT than the corresponding outputs in event based risk :-( So one has to change the names or to change the outputs to make them more similar, it is not as simple as exchanging the names.

Explanation of the difference:

1. The usual `avg_losses-rlzs` and `avg_losses-stats` are by asset while `reinsurance-avg_losses` is aggregated and there is only one dataset (no `-rlzs` and no `-stats`); my suggestion would be to change the name to `reinsurance-tot_losses`: they are total annual losses.
2. The usual `aggrisk` dataset when exported produces two files `aggrisk-stats` and `aggrisk-stats-policy`; now we are exporting a single `reinsurance-aggrisk` file aggregated by policy with all the realizations, not the stats. We can call such things
'Average Reinsurance By Policy', with the understanding that the overspill logic is missing, so by summing all policies you
will not get the same as the `reinsurance-tot_losses`.

**Comment by micheles** [comment]
I would just change to:
```
    'reinsurance-aggrisk': 'Average Reinsurance By Policy',
    'reinsurance-avg_losses': 'Average Portfolio Reinsurance'
```

**Comment by CatalinaYepes** [comment]
Based on your comments, I suggest keeping both outputs as avg. In the end both are "average aggregated losses". We could call them:

```
reinsurance-avg_losses_portfolio  --> Average Reinsurance
reinsurance-avg_losses_policy     --> Average Reinsurance By Policy
```
