### ISSUE TITLE
Standard separator for `aggregate_by` values

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#8750]
Currently, the [advanced manual](https://docs.openquake.org/oq-engine/advanced/master/event_based.html#aggregating-by-multiple-tags) defines the attribute `aggregate_by` as a field in which values are separated by commas.

<img width="925" alt="Screenshot 2023-05-16 at 10 09 00" src="https://github.com/gem/oq-engine/assets/6975363/f0ca8fa1-1664-4288-83a9-f04cd63ab90b">

However, for reinsurance calculations, the separation by commas doesn't work:
For example, when the reinsurance demo job.ini is modified to `aggregate_by = policy, NAME_1`, the following error appears:
```
openquake.baselib.InvalidFile: The field `aggregate_by = policy` in the /Users/cye/oq-engine/demos/risk/Reinsurance/job.ini file is required for reinsurance calculations. Got `aggregate_by = [['policy', 'NAME_1']]` instead.
```

For reinsurance calculations, the separation is by a semicolon: `aggregate_by = policy; NAME_1`

It will be important to have a consistent separator across calculators to avoid mistakes.

**Comment by micheles** [comment]
No, @CatalinaYepes, you do not understand. "," and ";" are different for a reason since they cover two different use cases.
"," means "multiplication" and ";" means sum; for instance

aggregate_by = region, occupancy

with R regione and O occupancies will give R * O outputs.

On the contrary

aggregate_by = region; occupancy

with aggregate by region, then by occupancy and produce R + O outputs.

**Comment by micheles** [comment]
The work to do is to see if this feature is documented in the manual and if not document it.

**Comment by ptormene** [comment]
Fast suggestion for the reinsurance, by @CatalinaYepes. It can be rephrased better, perhaps also adding a link when we explain the possibility for aggregation.

aggregate_by: it is possible to define multiple aggregation keys. However, for reinsurance calculations the policy key must be present, otherwise an error message will be raised.

Example for using multiple aggregation keys:
aggregate_by = policy; tag1

In this case aggregated loss_curves will be produced also for tag1 and policy, while reinsurance outputs are only produced for the policy.
