### ISSUE TITLE
Error in scenario calculations when conditioning the gmfs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#8833]
A particular combination of a `<multiPlanesRupture>` with a GMPE that requires the `ry0` distance (eg. `AbrahamsonEtAl2014` & `GulerceEtAl2017`) triggers this error, if station data is present in the calculation.

Error message:
`ValueError: could not broadcast input array from shape (9282,) into shape (22,)`

**To replicate the error:**

(see attached file) There are three variables for the calculations:
1. With or without conditioning to stations
1. Rupture geometry
1. GMPE logic tree

The issue appears for the combination: Stations:Seismic, gmlt:USGS, Rupture:USGS 
- If you run without conditioning (`gmlt:USGS, Rupture:USGS`), it works
- If you condition but changes the rupture (for example `GCMT, Stations:Seismic, gmlt:USGS, Rupture:GCMT`), it works
- If you condition but changes the gmlt (for example `GEM, Stations:Seismic, gmlt:GEM, Rupture:USGS`), it works

It’s that specific combination that generates the error.

**Comment by micheles** [comment]
This is likely caused by a *titanic error* in `event_based.event_based` that slipped though my code review: the lines
```python
                    station_sites = dstore.read_df('station_sites')
                    station_data = dstore.read_df('station_data')
```
cannot go there, anything reading functions must be execute by the master node and not by the workers. Moreover the station_sites must be a subset of the complete site collection and not an independent site collection. Therefore conditioned GMFs appear to work only by miracle.
