### ISSUE TITLE
KeyError raised in AkkarBommer2010SWISS01 for PGV

### ISSUE THREAD

**Issue by rizac** [gem/oq-engine#9263]
Hi all,

when asking for PGV in AkkarBommer2010SWISS01 we get a KeyError in the code:

https://github.com/gem/oq-engine/blob/b5eacb93707c6fbfecdf4385cb2d33a529c99f14/openquake/hazardlib/gsim/coeffs_table.py#L251C21-L251C21

Most likely this is due to AkkarBommer subclasses that should probably be defined only for PGA and SA (because in the COEFFS TABLE there is no PGV)

(Thanks also to @g-weatherill for helping writing this issue)

**Comment by micheles** [comment]
Seems to be the intended behavior, indeed the docstring of the class says
```
        :raises KeyError:
            If ``imt`` is not available in the table and no interpolation
            can be done.
```

**Comment by g-weatherill** [comment]
I don't think this was the intended behaviour of the GMPE, but perhaps the issue raised didn't provide a full enough explanation. 

`AkkarBommer2010SWISS01`, `AkkarBommer2010SWISS04` and `AkkarBommer2010SWISS08` all inherit from `AkkarBommer2010`, which is defined as supported for PGA, SA and PGV.  The sub-classes don't change the `DEFINED_FOR_INTENSITY_MEASURE_TYPES` attribute, so they are also indicted as being supported for PGA, SA and PGV. However, the Swiss subclasses use the rock adjustment factors here: https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/gsim/akkar_bommer_2010_swiss_coeffs.py, which are only defined for PGA and SA, but not for PGV. The outcome of this is that OQ will pass the validation checks if you try to run calculations with them using PGV but then later crash out with the`KeyError` that occurs when it tries to get the PGV coefficients from these tables.

The fix is just to update `DEFINED_FOR_INTENSITY_MEASURE_TYPES = {PGA, SA}` in the subclasses.

**Comment by micheles** [comment]
Ah, thanks Graeme, not it is clear.
