### ISSUE TITLE
NGAEastUSGSGMPE not working outside of unit tests

### ISSUE THREAD

**Issue by CB-quakemodel** [gem/oq-engine#9605]
The core NGAEastUSGSGMPE does not appear to work outside of the unit tests. Given a gmpe_table is not required anymore for the core gsim (based on the class docstring), specifying the gmpe alone as within the screenshot should work. I have tried in the area classical PSHA and this generates the following error:

![image](https://github.com/gem/oq-engine/assets/119606956/0dc10168-2eb5-48a3-be1d-758e37b4f392)

Thanks,

Chris

**Comment by g-weatherill** [comment]
It's been a long time since I did this but I don't think I intended for the NGAEastUSGSGMPE to be used directly as a class in itself. So Michele is right. It didn't make any sense to use it as a standalone GMPE, as the operation of the GMPE is specifically for what I recall was the 2018 US NSHM set of CEUS GMPEs, so it must be associated to one of the tables that are given in the aliases. I guess I hadn't precluded the possibility that one could pass a different table of ground motions than one of those used by the USGS, it just wasn't developed with that in mind.

**Comment by CB-quakemodel** [comment]
Thanks for the clarification. I misinterpreted from the docstring that we could instantiate the entire 2018 USGS CEUS GMPE set in a logic tree by not specifying a gmpe table, rather than this referring to the use of add_alias making specifying a gmpe table unnecessary. I'll open a PR clarifying the docstring slightly and link it
